// src/features/marketplace/components/AppCard.tsx

import React from 'react';
import { ShieldCheck, Download, ArrowUpCircle, ChevronRight } from 'lucide-react';
import { AppPack, ProcessingMode } from '../../../shared/mocks/apps';
import { useI18n } from '../../../i18n';
import FACard from '../../../ui/FACard';
import FATag from '../../../ui/FATag';
import { Popover, Tooltip, Button } from 'antd';

interface AppCardProps {
  app: AppPack;
  onClick: () => void;
}

const AppCard: React.FC<AppCardProps> = ({ app, onClick }) => {
  const { t } = useI18n();
  
  // 状态判定逻辑
  const hasUpdate = app.installedVersion && app.installedVersion !== app.version;
  const isInstalled = !!app.installedVersion && !hasUpdate;
  const isNotInstalled = !app.installedVersion;

  const displayLimit = 3;
  const uniqueModes: ProcessingMode[] = Array.from(new Set(app.capabilities.map(c => c.mode)));

  const getModeLabel = (mode: ProcessingMode) => {
    switch(mode) {
      case 'edge_realtime': return 'EDGE';
      case 'near_real_time_cloud': return 'CLOUD';
      case 'offline_batch': return 'BATCH';
      default: return (mode as string).toUpperCase();
    }
  };

  return (
    <FACard 
      hoverable 
      onClick={onClick}
      className={`relative flex flex-col h-[280px] overflow-hidden group border-border shadow-card bg-bg-card transition-all ${isInstalled ? 'ring-1 ring-success/5' : ''}`}
      density="compact"
    >
      {/* 1. Header: Icon + Title */}
      <div className="flex items-start gap-3 mb-3 shrink-0">
        <div className={`w-11 h-11 rounded-xl border p-2 flex items-center justify-center shrink-0 transition-colors ${isInstalled ? 'bg-success/5 border-success/10' : 'bg-bg-page border-border'}`}>
          <img src={app.icon} alt="" className="w-full h-full object-contain" />
        </div>
        <div className="min-w-0 flex-1 pt-0.5">
          <div className="flex items-center gap-1.5 min-w-0 overflow-hidden mb-0.5">
            <h3 className="text-fa-t5 font-fa-semibold text-text-primary truncate group-hover:text-brand transition-colors leading-tight m-0">
              {app.name}
            </h3>
            {app.signature === 'Verified' && <ShieldCheck size={14} className="text-success shrink-0" />}
          </div>
          <p className="text-fa-t6 font-fa-medium text-text-tertiary truncate tracking-tight m-0">{app.publisher}</p>
        </div>
      </div>

      {/* 2. Body: Metadata */}
      <div className="flex-1 flex flex-col min-h-0 space-y-3">
        <Tooltip title={app.description}>
          <p className="text-fa-t6 text-text-secondary truncate leading-relaxed m-0">
            {app.description}
          </p>
        </Tooltip>

        <div className="space-y-3">
          <div className="flex flex-col gap-1.5">
             <span className="text-fa-t7 font-fa-semibold font-mono text-text-tertiary uppercase tracking-widest text-[9px]">处理模式</span>
             <div className="flex flex-wrap gap-1.5">
                {uniqueModes.slice(0, displayLimit).map((mode, idx) => (
                  <FATag key={idx}>{getModeLabel(mode)}</FATag>
                ))}
             </div>
          </div>
          <div className="flex flex-col gap-1.5">
             <span className="text-fa-t7 font-fa-semibold font-mono text-text-tertiary uppercase tracking-widest text-[9px]">核心产物</span>
             <div className="flex flex-wrap gap-1.5">
                {app.expectedOutputs.slice(0, displayLimit).map((out, idx) => (
                  <FATag key={idx}>{out}</FATag>
                ))}
             </div>
          </div>
        </div>
      </div>

      {/* 3. Footer: Version + Context Actions */}
      <div className="mt-auto py-3 border-t border-divider flex items-center justify-between shrink-0">
        <div className="flex items-center gap-2">
          {isInstalled && <div className="w-1.5 h-1.5 rounded-full bg-success animate-pulse" />}
          <span className="text-fa-t7 font-fa-semibold font-mono text-text-tertiary uppercase tabular-nums">
            {isInstalled ? app.installedVersion : app.version}
          </span>
        </div>
        
        <div className="flex items-center gap-2">
          {isNotInstalled && (
            <Button type="primary" size="small" icon={<Download size={12} />} className="text-fa-t7 font-fa-semibold uppercase h-7 px-3">
              安装
            </Button>
          )}

          {hasUpdate && (
            <Button type="primary" size="small" icon={<ArrowUpCircle size={12} />} className="text-fa-t7 font-fa-semibold uppercase h-7 px-3 bg-warning border-none hover:bg-warning-hover">
              更新
            </Button>
          )}

          {isInstalled && (
            <Button size="small" className="text-fa-t7 font-fa-semibold uppercase h-7 px-2.5 text-text-tertiary border-border hover:text-brand flex items-center gap-1 group/btn">
              详情 <ChevronRight size={12} className="transition-transform group-hover/btn:translate-x-0.5" />
            </Button>
          )}
        </div>
      </div>
    </FACard>
  );
};

export default AppCard;

// src/features/marketplace/components/AppCard.vue

<script setup lang="ts">
import { computed } from 'vue';
import { ShieldCheck, Download, ChevronRight } from 'lucide-vue-next';
import type { AppPack } from '../types';

const props = defineProps<{
  app: AppPack;
}>();

const emit = defineEmits(['click']);

const isInstalled = computed(() => !!props.app.installedVersion);
const uniqueModes = computed(() => Array.from(new Set(props.app.capabilities.map(c => c.mode))));

const modeLabels: Record<string, string> = {
  edge_realtime: 'EDGE',
  near_real_time_cloud: 'CLOUD',
  offline_batch: 'BATCH'
};
</script>

<template>
  <div 
    @click="emit('click')"
    class="group bg-[rgba(var(--fa-bg-card),1)] border border-[rgba(var(--fa-border),1)] rounded-[12px] p-4 flex flex-col h-[280px] transition-all hover:border-[rgba(var(--fa-brand),0.4)] hover:shadow-[0_1px_3px_rgba(0,0,0,0.06)] cursor-pointer"
  >
    <!-- Header -->
    <div class="flex items-start gap-3 mb-4 shrink-0">
      <div class="w-12 h-12 rounded-xl bg-[rgba(var(--fa-bg-page),1)] border border-[rgba(var(--fa-border),1)] p-2 flex items-center justify-center">
        <img :src="app.icon" class="w-full h-full object-contain" />
      </div>
      <div class="min-w-0 flex-1">
        <div class="flex items-center gap-1.5 mb-0.5">
          <h3 class="text-[14px] font-semibold text-[rgba(var(--fa-text-primary),1)] truncate m-0 group-hover:text-[rgba(var(--fa-brand),1)] transition-colors">
            {{ app.name }}
          </h3>
          <ShieldCheck size="14" class="text-[rgba(var(--fa-success),1)] shrink-0" />
        </div>
        <p class="text-[12px] text-[rgba(var(--fa-text-tertiary),1)] m-0 truncate">{{ app.publisher }}</p>
      </div>
    </div>

    <!-- Body -->
    <div class="flex-1 space-y-3 min-h-0">
      <p class="text-[12px] text-[rgba(var(--fa-text-secondary),1)] line-clamp-2 leading-relaxed m-0">
        {{ app.description }}
      </p>
      
      <div class="space-y-2">
        <div class="flex flex-col gap-1">
          <span class="text-[10px] font-bold text-[rgba(var(--fa-text-tertiary),1)] uppercase tracking-widest">模式</span>
          <div class="flex flex-wrap gap-1.5">
            <span v-for="mode in uniqueModes" :key="mode" class="px-1.5 py-0.5 bg-[rgba(var(--fa-bg-page),1)] border border-[rgba(var(--fa-border),1)] rounded-[4px] text-[10px] font-mono font-bold text-[rgba(var(--fa-text-secondary),1)]">
              {{ modeLabels[mode] }}
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div class="mt-auto pt-3 border-t border-[rgba(var(--fa-divider),1)] flex items-center justify-between">
      <span class="text-[11px] font-mono font-bold text-[rgba(var(--fa-text-tertiary),1)]">
        {{ isInstalled ? app.installedVersion : app.version }}
      </span>
      
      <button v-if="!isInstalled" class="h-7 px-3 bg-[rgba(var(--fa-brand),1)] text-white rounded-[6px] text-[11px] font-bold uppercase tracking-widest flex items-center gap-1.5 hover:opacity-90 active:scale-95 transition-all">
        <Download size="12" /> 安装
      </button>
      <button v-else class="text-[11px] font-bold text-[rgba(var(--fa-brand),1)] uppercase flex items-center gap-1 group-hover:translate-x-0.5 transition-transform">
        详情 <ChevronRight size="12" />
      </button>
    </div>
  </div>
</template>
